name: C++ Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write

env:
  version: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build Project
        run: make

      - name: Create Directory to Binary
        run: mkdir -p release && mv bin/Program release/WebDomCompiler

      - name: Upload binary as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WebDomCompiler
          path: release/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: WebDomCompiler
          path: release/

      - name: Create GitHub Release and Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
